"""empty message

Revision ID: c5be792105e1
Revises: 371539f2034c
Create Date: 2024-01-29 13:20:44.832552

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'c5be792105e1'
down_revision = '371539f2034c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wanted_mounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mount_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mount_id'], ['mounts.blizzId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'mount_id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE wanted_mounts SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wanted_mounts')
    # ### end Alembic commands ###
